# Generated by Django 2.2.1 on 2019-06-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.CharField(max_length=300)),
                ('year', models.PositiveSmallIntegerField(blank=True)),
                ('month', models.PositiveSmallIntegerField(blank=True)),
                ('day', models.PositiveSmallIntegerField(blank=True)),
                ('date', models.CharField(max_length=200)),
                ('hour', models.PositiveSmallIntegerField(blank=True)),
                ('minute', models.PositiveSmallIntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('roadtype', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('dead', models.PositiveSmallIntegerField(blank=True)),
                ('hurt', models.PositiveSmallIntegerField(blank=True)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('rain', models.CharField(blank=True, max_length=100)),
                ('wind', models.CharField(blank=True, max_length=100)),
                ('temp', models.CharField(blank=True, max_length=100)),
                ('naturl', models.CharField(blank=True, max_length=100)),
                ('p1_name', models.CharField(blank=True, max_length=100)),
                ('p1_birthday', models.CharField(blank=True, max_length=100)),
                ('p1_age', models.PositiveSmallIntegerField(blank=True)),
                ('p1_id', models.CharField(blank=True, max_length=100)),
                ('p1_driveyear', models.PositiveSmallIntegerField(blank=True)),
                ('p1_type', models.CharField(blank=True, max_length=100)),
                ('p1_dayget', models.CharField(blank=True, max_length=100)),
                ('p1_cartype', models.CharField(blank=True, max_length=50)),
                ('p1_numoncar', models.PositiveSmallIntegerField(blank=True)),
                ('p1_carid', models.CharField(blank=True, max_length=50)),
                ('p1_blame', models.CharField(blank=True, max_length=100)),
                ('p1_sex', models.CharField(blank=True, max_length=50)),
                ('p2_name', models.CharField(blank=True, max_length=50)),
                ('p2_birthday', models.CharField(blank=True, max_length=100)),
                ('p2_age', models.PositiveSmallIntegerField(blank=True)),
                ('p2_id', models.CharField(blank=True, max_length=50)),
                ('p2_driveyear', models.PositiveSmallIntegerField(blank=True)),
                ('p2_type', models.CharField(blank=True, max_length=50)),
                ('p2_dayget', models.CharField(blank=True, max_length=50)),
                ('p2_cartype', models.CharField(blank=True, max_length=50)),
                ('p2_numoncar', models.PositiveSmallIntegerField(blank=True)),
                ('p2_carid', models.CharField(blank=True, max_length=50)),
                ('p2_blame', models.CharField(blank=True, max_length=50)),
                ('p2_sex', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
    ]
