# Generated by Django 2.2.3 on 2019-07-11 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0004_auto_20190620_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accident_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
